app-template:
  controllers:
    unmanic:
      labels:
        backup/retain: quaterly
      type: statefulset
      pod:
        enableServiceLinks: false
        runtimeClassName: nvidia
        labels:
          runtime-class: nvidia
      containers:
        unmanic:
          image:
            repository: josh5/unmanic
            tag: latest

          command: ["/usr/local/bin/unmanic-service"] # Hard requirement for running rootless
        
          env:
            TZ: Europe/Madrid
            NVIDIA_VISIBLE_DEVICES: 0
            HOME: "/config" # Hard requirement for running rootless

          resources:
            requests:
              cpu: 100m
              memory: 1800Mi
            limits:
              cpu: 10000m #limit to 10 cores
              memory: 4000Mi
              nvidia.com/gpu: "1"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5

  service:
    unmanic:
      controller: unmanic
      ports:
        http:
          port: 8888

  ingress:
    unmanic:
      enabled: true
      className: nginx-internal
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      hosts:
      - host: &host unmanic.internal.dbcloud.org
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: unmanic
            port: http
      tls:
      - hosts:
        - *host
        secretName: unmanic-tls-certificate

    external:
      enabled: true
      className: nginx-external
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/target: dbcloud.org
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
        nginx.ingress.kubernetes.io/auth-url: https://auth.dbcloud.org/oauth2/auth?allowed_groups=unmanicUsers
        nginx.ingress.kubernetes.io/auth-signin: https://auth.dbcloud.org/oauth2/start
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      hosts:
      - host: &host unmanic.dbcloud.org
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: unmanic
            port: http
      tls:
      - hosts:
        - *host
        secretName: unmanic-external-tls-certificate

  defaultPodOptions:
    securityContext:
      runAsUser: 995
      runAsGroup: 991
      fsGroup: 991
      fsGroupChangePolicy: "OnRootMismatch"

  persistence:
    config:
      enabled: true
      globalMounts:
      - path: /config
      existingClaim: config-unmanic
    peliculas:
      enabled: true
      type: hostPath
      hostPath: /datasets/peliculas
      globalMounts:
      - path: /library/peliculas
    series:
      enabled: true
      type: hostPath
      hostPath: /datasets/series
      globalMounts:
      - path: /library/series
    music:
      enabled: true
      type: hostPath
      hostPath: /datasets/music
      globalMounts:
      - path: /library/music
    tmp:
      enabled: true
      globalMounts:
      - path: /tmp/unmanic
      existingClaim: tmp-unmanic
