alexa:
  smart_home:
    locale: es-ES
    filter:
      include_entities:
        - switch.luz_dormitorio
        - switch.luz_cocina
        - switch.luz_pasillo
        - switch.luz_invitados
        - switch.luz_despacho
        - switch.luz_ventilador_salon
        - switch.luz_lampara_salon
        - switch.luz_izquierda_sofa
        - switch.luz_derecha_sofa
        - switch.luz_mesa_cocina
        - switch.luz_entrada
        - switch.luz_terraza
        - switch.luz_tendedero
        - switch.luz_encimera
        - switch.luz_entrada_dormitorio
        - switch.luz_bano_dormitorio
        - switch.luz_ducha_dormitorio
        - cover.persiana_salon
        - cover.persiana_invitados
        - cover.persiana_dormitorio
        - cover.persiana_despacho
        - fan.ventilador_despacho
        - fan.ventilador_dormitorio
        - fan.ventilador_invitados
        - fan.ventilador_salon
        - binary_sensor.puerta_entrada
        - climate.radiador_despacho
        - climate.radiador_dormitorio
        - switch.modo_cocinar_stateful_scene
        - switch.modo_cena_stateful_scene
        - switch.modo_pelicula_stateful_scene
    entity_config:
      climate.radiador_despacho:
        name: "Radiador del despacho"
        description: "Controla la luz temperatura del radiador del despacho"
        display_categories: THERMOSTAT
      climate.radiador_dormitorio:
        name: "Radiador del dormitorio"
        description: "Controla la luz temperatura del radiador del dormitorio"
        display_categories: THERMOSTAT
      switch.luz_izquierda_sofa:
        name: "Lámpara izquierda del sofa del salón"
        description: "Controla la luz de la lámpara izquierda del sofa del salón"
        display_categories: LIGHT
      switch.luz_derecha_sofa:
        name: "Lámpara derecha del sofa del salón"
        description: "Controla la luz de la lámpara derecha del sofa del salón"
        display_categories: LIGHT
      switch.luz_lampara_salon:
        name: "Lámpara del salón"
        description: "Controla la luz de la lámpara del salón"
        display_categories: LIGHT
      switch.luz_dormitorio:
        name: "Luz del dormitorio"
        description: "Controla la luz del dormitorio"
        display_categories: LIGHT
      switch.luz_cocina:
        name: "Luz de la cocina"
        description: "Controla la luz de la cocina"
        display_categories: LIGHT
      switch.luz_pasillo:
        name: "Luz del pasillo"
        description: "Controla la luz del pasillo"
        display_categories: LIGHT
      switch.luz_invitados:
        name: "Luz de la habitacion de invitados"
        description: "Controla la luz de la habitacion de invitados"
        display_categories: LIGHT
      switch.luz_despacho:
        name: "Luz del despacho"
        description: "Controla la luz del despacho"
        display_categories: LIGHT
      switch.luz_ventilador_salon:
        name: "Luz del ventilador del salón"
        description: "Controla la luz del ventilador del salón"
        display_categories: LIGHT
      switch.luz_mesa_cocina:
        name: "Luz de la mesa de la cocina"
        description: "Controla la luz de la mesa de la cocina"
        display_categories: LIGHT
      switch.luz_entrada:
        name: "Luz de la entrada"
        description: "Controla la luz de la entrada"
        display_categories: LIGHT
      switch.luz_terraza:
        name: "Luz de la terraza"
        description: "Controla la luz de la terraza"
        display_categories: LIGHT
      switch.luz_tendedero:
        name: "Luz del tendedero"
        description: "Controla la luz del tendedero"
        display_categories: LIGHT
      switch.luz_encimera:
        name: "Luz de la encimera"
        description: "Controla la luz de la encimera"
        display_categories: LIGHT
      switch.luz_entrada_dormitorio:
        name: "Luz de la entrada del dormitorio"
        description: "Controla la luz de la entrada del dormitorio"
        display_categories: LIGHT
      switch.luz_bano_dormitorio:
        name: "Luz del baño del dormitorio"
        description: "Controla la luz del baño del dormitorio"
        display_categories: LIGHT
      switch.luz_ducha_dormitorio:
        name: "Luz de la ducha del dormitorio"
        description: "Controla la luz de la ducha del dormitorio"
        display_categories: LIGHT
      cover.persiana_despacho:
        name: "Persiana del despacho"
        description: "Controla la persiana del despacho"
        display_categories: EXTERIOR_BLIND
      cover.persiana_dormitorio:
        name: "Persiana del dormitorio"
        description: "Controla la persiana del dormitorio"
        display_categories: EXTERIOR_BLIND
      cover.persiana_invitados:
        name: "Persiana de la habitacion de invitados"
        description: "Controla la persiana de la habitacion de invitados"
        display_categories: EXTERIOR_BLIND
      cover.persiana_salon:
        name: "Persiana del salón"
        description: "Controla la persiana del salón"
        display_categories: EXTERIOR_BLIND
      fan.ventilador_despacho:
        name: "Ventilador del despacho"
        description: "Controla el ventilador del despacho"
        display_categories: FAN
      fan.ventilador_dormitorio:
        name: "Ventilador del dormitorio"
        description: "Controla el ventilador del dormitorio"
        display_categories: FAN
      fan.ventilador_invitados:
        name: "Ventilador del cuarto de invitados"
        description: "Controla el ventilador del cuarto de invitados"
        display_categories: FAN
      fan.ventilador_salon:
        name: "Ventilador del salón"
        description: "Controla el ventilador del salón"
        display_categories: FAN
      binary_sensor.puerta_entrada:
        name: "Puerta de la entrada"
        description: "Monitoriza el estado de la puerta de entrada"
        display_categories: DOOR
      switch.modo_cocinar_stateful_scene:
        name: "Modo de cocinar"
        description: "Activa el modo cocinar"
        display_categories: SWITCH
      switch.modo_cena_stateful_scene:
        name: "Modo de cocinar"
        description: "Activa el modo cena"
        display_categories: SWITCH
      switch.modo_pelicula_stateful_scene:
        name: "Modo pelicula"
        description: "Activa el modo pelicula o peli"
        display_categories: SWITCH
