app-template:
  controllers:
    elsuenodediana:
      labels:
        backup/retain: quarterly
      type: statefulset
      containers:
        elsuenodediana:
          image:
            repository: prestashop/prestashop
            tag: 8.1.5

          env:
            TZ: Europe/Madrid
            DB_SERVER: mysql
            DB_NAME: prestashop
            DB_USER: root
            DB_PASSWD: admin
            PS_FOLDER_ADMIN: admin8491
            PS_FOLDER_INSTALL: install8491

          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 600
                periodSeconds: 5

          resources:
            requests:
              cpu: 150m
              memory: 170Mi
            limits:
              memory: 700Mi
          ports:
          - containerPort: 80
            name: elsuenodediana


    mysql:
      labels:
        backup/retain: quarterly
      type: statefulset
      containers:
        mysql:
          image:
            repository: mysql
            tag: 5.7
          env:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: prestashop
          resources:
            requests:
              cpu: 150m
              memory: 170Mi
            limits:
              memory: 700Mi
          ports:
          - containerPort: 3306
            name: mysql


    phpmyadmin-elsuenodediana:
      labels:
        backup/retain: quarterly
      type: statefulset
      containers:
        phpmyadmin-elsuenodediana:
          image:
            repository: phpmyadmin/phpmyadmin
            tag: latest
          env:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
          resources:
            requests:
              cpu: 150m
              memory: 170Mi
            limits:
              memory: 700Mi
          ports:
          - containerPort: 80
            name: phpmyadmin-elsuenodediana


  service:
    elsuenodediana:
      controller: elsuenodediana
      ports:
        http:
          port: 80

    phpmyadmin-elsuenodediana:
      controller: phpmyadmin-elsuenodediana
      ports:
        http:
          port: 80

  ingress:
    elsuenodediana:
      enabled: true
      className: nginx-internal
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      hosts:
      - host: &host elsuenodediana.internal.dbcloud.org
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: elsuenodediana
            port: http
      tls:
      - hosts:
        - *host
        secretName: elsuenodediana-tls-certificate

    phpmyadmin-elsuenodediana:
      enabled: true
      className: nginx-internal
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      hosts:
      - host: &host phpmyadmin-elsuenodediana.internal.dbcloud.org
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: phpmyadmin-elsuenodediana
            port: http
      tls:
      - hosts:
        - *host
        secretName: phpmyadmin-elsuenodediana-tls-certificate

    external:
      enabled: true
      className: nginx-external
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/target: dbcloud.org
        cert-manager.io/cluster-issuer: letsencrypt-prod-dns
        nginx.ingress.kubernetes.io/auth-url: https://auth.dbcloud.org/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.dbcloud.org/oauth2/start
      hosts:
      - host: &host elsuenodediana.dbcloud.org
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: elsuenodediana
            port: http
      tls:
      - hosts:
        - *host
        secretName: elsuenodediana-external-tls-certificate
  defaultPodOptions:
    securityContext:
      runAsUser: 995
      runAsGroup: 991
      fsGroup: 991
      fsGroupChangePolicy: "OnRootMismatch"

  persistence:
    config:
      enabled: true
      existingClaim: config-elsuenodediana
      advancedMounts:
        elsuenodediana:
          elsuenodediana:
          - path: /var/www/html
    db:
      enabled: true
      existingClaim: db-elsuenodediana
      advancedMounts:
        mysql:
          mysql:
          - path: /var/lib/mysql
