apiVersion: v1
kind: Namespace
metadata:
  name: frigate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-files
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-logs
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - name: frigate
          image:  ghcr.io/blakeblackshear/frigate:stable
          ports:
            - containerPort: 8971
            - containerPort: 8554
          volumeMounts:
            - mountPath: /config
              name: frigate-config
            - mountPath: /media/frigate
              name: frigate-files
            - mountPath: /dev/shm
              name: frigate-logs
          securityContext:
            privileged: true
      volumes:
        - name: frigate-config
          persistentVolumeClaim:
            claimName: frigate-config
        - name: frigate-files
          persistentVolumeClaim:
            claimName: frigate-files
        - name: frigate-logs
          persistentVolumeClaim:
            claimName: frigate-logs

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    app: frigate
  type: NodePort
  ports:
    - protocol: TCP
      port: 8971
      targetPort: 8971
      nodePort: 8971
    - protocol: TCP
      port: 8554
      targetPort: 8554
      nodePort: 8554