zfs-localpv:
  zfsNode:
    resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 32Mi
    # requests:
    #   cpu: 10m
    #   memory: 32Mi
  zfsController:
    resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 32Mi
    # requests:
    #   cpu: 10m
    #   memory: 32Mi
    snapshotter:
      extraArgs:
        - -v=1
    snapshotController:
      extraArgs:
        - -v=1
